In [1]:
! pip install scikit-learn
! pip install ntlk
! pip install numpy
! pip install scipy
! pip install pandas

ERROR: Could not find a version that satisfies the requirement ntlk (from versions: none)
ERROR: No matching distribution found for ntlk


In [3]:
from sklearn.preprocessing import LabelEncoder

lenc = LabelEncoder()
x = ["A", "B", "C", "B", "A"]
x_enc = lenc.fit_transform(x)

print(lenc.classes_)
# >> ['A' 'B' 'C']
print(x_enc)
# >> [0 1 2 1 0]

['A' 'B' 'C']
[0 1 2 1 0]


In [4]:
from sklearn.preprocessing import OneHotEncoder

x = [["Pop"], ["Rock"], ["Rock"]]
oenc = OneHotEncoder()
x_enc = oenc.fit_transform(x)
print(oenc.categories_)
# >> [array(['Pop', 'Rock'], dtype=object)]
print(x_enc.toarray())
# >> [[1. 0.] [0. 1.] [0. 1.]]

[array(['Pop', 'Rock'], dtype=object)]
[[1. 0.]
 [0. 1.]
 [0. 1.]]


In [5]:
from sklearn.feature_extraction.text import CountVectorizer

text = ["I like NLP like ML"]

vectorizer = CountVectorizer()
# you can also create count vectors for n-grams
# e.g., CountVectorizer(ngram_range=(2,2)) for bigrams
vectorizer.fit(text)
vector = vectorizer.transform(text)

print(vectorizer.vocabulary_)
# >> {'like': 0, 'nlp': 2, 'ml': 1}
print(vector.toarray())
# >> [[2 1 1]]

{'like': 0, 'nlp': 2, 'ml': 1}
[[2 1 1]]


In [6]:
from sklearn.feature_extraction.text import HashingVectorizer
text = ["I like natural language processing"]
vectorizer = HashingVectorizer(n_features=10)
vector = vectorizer.transform(text)
print(vector.shape)
# >> (1, 10)
print(vector.toarray())
# >> [[  0.40824829 0. 0. 0. -0.40824829
# -0.81649658 0. 0. 0. 0.]]

(1, 10)
[[ 0.40824829  0.          0.          0.         -0.40824829 -0.81649658
   0.          0.          0.          0.        ]]


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

x = ["i like nlp", "nlp is fun", "learn and like nlp"]
vectorizer = TfidfVectorizer()
vectorizer.fit(x)
tfidf_x = vectorizer.transform(x)
print(tfidf_x)

  (0, 5)	0.6133555370249717
  (0, 4)	0.7898069290660905
  (1, 5)	0.3853716274664007
  (1, 2)	0.652490884512534
  (1, 1)	0.652490884512534
  (2, 5)	0.34520501686496574
  (2, 4)	0.444514311537431
  (2, 3)	0.5844829010200651
  (2, 0)	0.5844829010200651


In [8]:
import numpy as np
import pandas as pd
import scipy
from nltk.tokenize import word_tokenize

def create_cooccurrence_matrix(sentences, window_size=2):
    vocabulary = {}
    data = []
    row = []
    col = []
    for sentence in sentences:
        tokens = [
            token
            for token in word_tokenize(sentence.strip())
            if token != u""
        ]
        for pos, token in enumerate(tokens):
            i = vocabulary.setdefault(token, len(vocabulary))
            start = max(0, pos-window_size)
            end = min(len(tokens), pos+window_size+1)
            for pos2 in range(start, end):
                j = vocabulary.setdefault(tokens[pos2], len(vocabulary))
                data.append(1.)
                row.append(i)
                col.append(j)
    cooc_matrix_sparse = scipy.sparse.coo_matrix(
        (data, (row, col))
    )
    return vocabulary, cooc_matrix_sparse
sentences = [
    'grass green',
    'sky blue',
    'green grass forest',
    'blue sky clouds'
]

vocab, coocc_matrix = create_cooccurrence_matrix(sentences)
df_coocc  = pd.DataFrame(
    coocc_matrix.todense(), index=vocab.keys(), columns = vocab.keys()
)
df_coocc = df_coocc.sort_index()[sorted(vocab.keys())]

print(df_coocc)
# >>	   blue  clouds  forest  grass  green  sky
# blue	 2.0	 1.0	 0.0	0.0	0.0	2.0
# clouds   1.0	 1.0	 0.0	0.0	0.0	1.0
# forest   0.0	 0.0	 1.0	1.0	1.0	0.0
# grass	0.0	 0.0	 1.0	2.0	2.0	0.0
# green	0.0	 0.0	 1.0	2.0	2.0	0.0
# sky	  2.0	 1.0	 0.0	0.0	0.0	2.0

        blue  clouds  forest  grass  green  sky
blue     2.0     1.0     0.0    0.0    0.0  2.0
clouds   1.0     1.0     0.0    0.0    0.0  1.0
forest   0.0     0.0     1.0    1.0    1.0  0.0
grass    0.0     0.0     1.0    2.0    2.0  0.0
green    0.0     0.0     1.0    2.0    2.0  0.0
sky      2.0     1.0     0.0    0.0    0.0  2.0


In [9]:
! pip install spacy
! python -m spacy download "en_core_web_sm"

2022-12-02 16:04:13.456301: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 5.0 MB/s eta 0:00:0000:0100:01m


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [10]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(u'hot chocolate is filling')

doc.vector

/Users/jyotikasingh/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-12-02 16:04:29.416094: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


array([ 0.13381374,  0.36508197,  0.30986196, -0.09674297,  0.19606659,
       -0.27809095, -0.7400991 ,  0.42656842, -0.25318536, -0.04447048,
       -0.19573873, -0.6232816 ,  0.09217687, -0.09037766,  0.50237906,
        0.48807704, -0.40230915, -0.25389698,  0.22596228,  0.62372756,
       -0.3362951 ,  0.1865205 ,  0.96728605, -0.08843744, -0.35482422,
       -0.1544794 , -0.32330373, -0.13426837,  0.02369949,  0.06470922,
       -0.30293936,  0.3435747 , -0.05029403,  0.06842262, -0.37998134,
       -0.728451  ,  0.01250184,  0.17351228,  1.1982682 ,  0.42723656,
        0.19957814,  0.37723488,  1.3086611 ,  0.02693128, -0.32037276,
        0.13329065,  0.15267858, -0.23527801,  0.27066565, -0.02691245,
       -0.00457121, -0.10034095,  0.1442278 , -0.09963769,  0.01597232,
        0.52032745, -0.00658892, -0.08868112,  0.35356194,  0.16364096,
       -0.16582608, -0.27053612,  0.25772235, -0.4756692 , -0.68347526,
       -0.36431193,  0.26009572, -0.9408033 , -0.15450715, -0.84

# Gensim word2vec

In [4]:
! pip install gensim

In [6]:
import gensim.downloader as api

model = api.load('word2vec-google-news-300')
model['river']

array([ 8.36181641e-03,  1.81640625e-01,  8.98437500e-02,  7.22656250e-02,
        1.18652344e-01, -9.17968750e-02, -1.50390625e-01, -9.08203125e-02,
        2.57812500e-01,  3.15856934e-03,  2.42187500e-01, -7.32421875e-02,
        6.15234375e-02,  2.14843750e-02, -1.86767578e-02, -3.14453125e-01,
       -4.54711914e-03, -1.28906250e-01,  3.89099121e-03, -1.14257812e-01,
       -1.32812500e-01,  4.39453125e-02, -6.44531250e-02, -4.19921875e-02,
        3.32031250e-01, -3.55468750e-01, -1.86523438e-01, -6.25000000e-02,
        1.13769531e-01, -1.62109375e-01, -2.09960938e-01,  2.79296875e-01,
       -1.16210938e-01,  5.54199219e-02, -2.55859375e-01, -1.65039062e-01,
        6.49414062e-02, -1.36718750e-02, -3.63769531e-02, -9.61914062e-02,
       -5.35156250e-01,  3.97949219e-02,  2.29492188e-01, -7.76367188e-02,
       -2.85156250e-01, -3.63281250e-01, -5.56640625e-02,  1.27929688e-01,
       -4.80957031e-02,  2.36328125e-01,  2.94921875e-01, -5.63964844e-02,
        8.25195312e-02, -

# fastText

In [13]:
from gensim.models import FastText

tokens_doc = [
    ['I', 'like', 'nlp'],
    ['nlp', 'and', 'machine', 'learning']
]
fast = FastText(
    tokens_doc,
    size=20,
    window=1,
    min_count=1,
    workers=5,
    min_n=1, max_n=2
)
# vector for word 'nlp'
fast.wv['nlp']

array([-0.01679415,  0.00839234, -0.02177516, -0.00593151, -0.00834616,
       -0.00154076, -0.00882761,  0.01569091, -0.01973948,  0.00249172,
       -0.00890919, -0.02117214, -0.01711161, -0.00537765, -0.01926894,
       -0.00029109, -0.01233554,  0.00183896, -0.0160269 , -0.00282335],
      dtype=float32)

# GloVe

In [16]:
! pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9657 sha256=989ce580e106b4701d57190230a7fb0a580f39905ac1455e64c50b69def401a8
  Stored in directory: /Users/jyotikasingh/Library/Caches/pip/wheels/04/5f/3e/46cc37c5d698415694d83f607f833f83f0149e49b3af9d0f38
Successfully built wget


In [19]:
! python -m wget http://nlp.stanford.edu/data/glove.6B.zip
! unzip glove*.zip

100% [..................................................] 862182613 / 8621826133440 / 862182613
Saved under glove.6B.zip
Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [21]:
import numpy as np

emmbed_dict = {}
with open('glove.6B.200d.txt', 'r') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], 'float32')
        emmbed_dict[word] = vector
print(emmbed_dict['river'])

[-0.3396    -0.034968   0.50918   -0.21131    0.12505   -0.1273
 -0.49713   -0.42766   -1.1465    -1.03      -0.68081   -0.8441
 -0.53539   -0.34949    0.35617    0.084823  -0.30111   -0.015468
  0.20779   -0.21195    0.06292    1.538     -0.053514   0.82091
  0.40287   -0.6614     0.36424    0.31173   -0.39355    0.30448
  0.29614   -0.15658   -0.4304     0.10324    0.49861   -0.74793
 -1.2427     0.57625    0.40451   -0.38491   -0.43445    0.49646
  0.16707    0.44802    0.11118    0.42416    0.3119     0.9609
 -0.74435    0.83122   -0.20885    0.76589    0.5018    -0.23054
  0.069079   0.79359   -0.70704   -0.040888   0.35677    0.63979
 -0.45005    0.37254    0.020079  -0.25263   -0.46693    0.34979
 -0.20673    0.47023    0.26935   -1.0315    -0.33268   -0.72155
 -0.43251    0.38386    0.41144    1.0171     0.85954    0.12452
  0.89378   -0.52045    0.25741    0.37725   -1.0493    -0.21989
  0.0077625 -0.90762    0.078311  -0.50351    0.25786   -0.72913
  0.25364    0.40323   -0.4

# ELMo

In [22]:
! pip install tensorflow
! pip install tensorflow-hub

  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)


In [23]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

# Load pre trained ELMo model
elmo = hub.Module(
    "https://tfhub.dev/google/elmo/3",
    trainable=True
)

# create an instance of ELMo
embeddings = elmo(
    [
        "I love to watch TV",
        "I am wearing a wrist watch"
    ],
    signature="default",
    as_dict=True)["elmo"]
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

print('Word embeddings for the word "watch" in the 1st sentence')
print(sess.run(embeddings[0][3]))
print('Word embeddings for the word "watch" in the 2nd sentence')
print(sess.run(embeddings[1][5]))


2022-12-02 16:27:38.260300: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.
2022-12-02 16:27:38.676278: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled


Word embeddings for the word "watch" in the 1st sentence
[ 0.14079624 -0.15788543 -0.00950474 ...  0.43005997 -0.52887076
  0.0632787 ]
Word embeddings for the word "watch" in the 2nd sentence
[-0.08213369  0.01050352 -0.01454161 ...  0.48705414 -0.5445795
  0.52623963]


# Universal sentence encoder

In [2]:
! pip install tensorflow
! pip install tensorflow_hub


In [1]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf

tf.enable_eager_execution()

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

sentences = [
    "I love to watch TV",
    "I am wearing a wrist watch"
]
embeddings = embed(sentences)

embeddings.numpy()

2022-12-02 16:52:15.100294: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-02 16:52:21.248141: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


array([[ 0.04982673, -0.03076092, -0.00110719, ..., -0.06628991,
         0.10678975, -0.02064821],
       [-0.00369536,  0.03064634, -0.05556111, ...,  0.01751419,
         0.03164959, -0.05139377]], dtype=float32)

# Transformers

In [24]:
! pip install transformers
! pip install sentence-transformers


In [25]:
from sentence_transformers import SentenceTransformer

docs = ["NLP method for feature extraction."]
sbert = SentenceTransformer('bert-base-nli-mean-tokens')
sentence_embeddings_BERT = sbert.encode(docs)
print(sentence_embeddings_BERT)

[[-4.50781614e-01 -2.76739091e-01  1.25894403e+00  1.99568361e-01
   6.88663721e-01  4.79360372e-01 -4.22404706e-01  4.28741455e-01
   3.97531956e-01 -3.00607849e-02 -5.40209949e-01  8.14363241e-01
  -1.78754460e-02  9.26031694e-02  2.50436634e-01  2.09438324e-01
  -7.44030774e-01 -2.34441549e-01  5.06882131e-01 -7.73964496e-03
   4.78665084e-01  4.08504829e-02 -8.53223801e-01 -4.83158231e-02
   9.02073756e-02 -3.96714002e-01  1.76787242e-01 -7.34953165e-01
  -9.87483859e-01  3.26186121e-01 -3.71115565e-01 -9.70747411e-01
   2.89142013e-01 -4.40381438e-01 -1.95847973e-01  3.24776113e-01
   1.32101119e-01 -6.24954849e-02 -1.96072876e-01  1.38612688e-01
   4.79865968e-01  3.37879471e-02  5.12158096e-01  6.33963823e-01
  -1.61993551e+00 -4.23679680e-01 -5.07638216e-01  1.80900350e-01
  -1.03218031e+00 -8.41399193e-01 -1.54714417e+00 -1.14395283e-02
  -6.24203943e-02  3.39939117e-01 -5.00815630e-01  6.85738921e-01
   8.94497156e-01 -1.35711336e+00  1.67555660e-01  2.49044046e-01
   9.95903

In [26]:
from transformers import pipeline

feat_extractor = pipeline("feature-extraction")
feature = feat_extractor("NLP method for feature extraction.")
print(feature)

No model was supplied, defaulted to distilbert-base-cased (https://huggingface.co/distilbert-base-cased)
Some weights of the model checkpoint at distilbert-base-cased were not used when initializing DistilBertModel: ['vocab_transform.bias', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_transform.weight', 'vocab_projector.bias', 'vocab_layer_norm.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[[[0.5642114281654358, 0.1064816564321518, 0.05079559236764908, -0.3685210347175598, -0.6029025912284851, -0.04557185247540474, 0.11228156089782715, 0.052640464156866074, 0.04195073992013931, -1.1887236833572388, -0.47542035579681396, 0.1693207025527954, -0.18549206852912903, 0.04103276878595352, -0.5473499894142151, 0.08845296502113342, 0.3194519281387329, 0.2894560694694519, -0.02468882128596306, -0.2969137728214264, -0.002839411608874798, -0.1750221699476242, 0.739684522151947, -0.2900165617465973, 0.16867266595363617, -0.059480562806129456, 0.47460073232650757, 0.16146941483020782, -0.16713635623455048, 0.43525430560112, 0.03017815202474594, 0.3116859495639801, 0.07316062599420547, 0.08993715047836304, -0.421871542930603, 0.1555507928133011, -0.12425709515810013, -0.43839848041534424, -0.14010705053806305, -0.041934993118047714, -0.5232452154159546, 0.12195662409067154, 0.6656383275985718, -0.23125667870044708, 0.22864119708538055, -0.6247425079345703, -0.016831988468766212, 0.0836